import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Semantic contract — forest/cream/gold
        forest: {
          DEFAULT: 'var(--forest)',
          deep: 'var(--forest-deep)',
          light: 'var(--forest-light)',
        },
        cream: {
          DEFAULT: 'var(--cream)',
          muted: 'var(--cream-muted)',
          faint: 'var(--cream-faint)',
        },
        gold: {
          DEFAULT: 'var(--gold)',
          light: 'var(--color-gold-light)',
          dark: 'var(--color-gold-dark)',
          pale: 'var(--color-gold-pale)',
        },
        ink: 'var(--ink)',
        // Legacy aliases — keep for components not yet migrated
        black: {
          DEFAULT: 'var(--color-black)',
          light: 'var(--color-gray-dark)',
        },
        gray: {
          dark: 'var(--color-gray-dark)',
          medium: 'var(--color-gray-medium)',
          light: 'var(--color-gray-light)',
        },
        textPrimary: 'var(--color-text-primary)',
        textSecondary: 'var(--color-text-secondary)',
        textTertiary: 'var(--color-text-tertiary)',
        textInverse: 'var(--color-text-inverse)',
        cta: {
          DEFAULT: 'var(--color-gold)',
          hover: 'var(--color-gold-light)',
          text: 'var(--color-text-inverse)',
        },
        status: {
          success: 'var(--color-success)',
          warning: 'var(--color-warning)',
          error: 'var(--color-error)',
        },
        'black-green': 'var(--color-black-green)',
        'surface': 'var(--color-surface)',
        'surface-raised': 'var(--color-surface-raised)',
        goldTransparent10: 'var(--color-gold-transparent-10)',
        goldTransparent30: 'var(--color-gold-transparent-30)',
        goldTransparent50: 'var(--color-gold-transparent-50)',
        goldTransparent70: 'var(--color-gold-transparent-70)',
      },
      fontFamily: {
        display: ['var(--font-display)', 'serif'],
        body: ['var(--font-body)', 'sans-serif'],
        mono: ['var(--font-mono)', 'monospace'],
      },
      fontSize: {
        '2xs': '0.625rem',
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        base: 'var(--text-base)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
        '4xl': 'var(--text-4xl)',
        '5xl': 'var(--text-5xl)',
        '6xl': 'var(--text-6xl)',
        '7xl': 'var(--text-7xl)',
        '8xl': 'var(--text-8xl)',
      },
      spacing: {
        '0': 'var(--space-0)',
        '1': 'var(--space-1)',
        '2': 'var(--space-2)',
        '3': 'var(--space-3)',
        '4': 'var(--space-4)',
        '5': 'var(--space-5)',
        '6': 'var(--space-6)',
        '7': 'var(--space-7)',
        '8': 'var(--space-8)',
        '9': 'var(--space-9)',
        '10': 'var(--space-10)',
        '11': 'calc(var(--space-unit) * 48)',
        '12': 'calc(var(--space-unit) * 64)',
        '14': 'calc(var(--space-unit) * 96)',
        '16': 'calc(var(--space-unit) * 128)',
        '20': 'calc(var(--space-unit) * 192)',
        '24': 'calc(var(--space-unit) * 256)',
        '28': 'calc(var(--space-unit) * 320)',
        '32': 'calc(var(--space-unit) * 384)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        none: 'none',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        inner: 'var(--shadow-inner)',
        'gold-sm': 'var(--shadow-gold)',
        'gold-md': 'var(--shadow-gold-lg)',
        'gold-lg': 'var(--shadow-gold-lg)',
      },
      screens: {
        xs: 'var(--breakpoint-xs)',
        sm: 'var(--breakpoint-sm)',
        md: 'var(--breakpoint-md)',
        lg: 'var(--breakpoint-lg)',
        xl: 'var(--breakpoint-xl)',
        '2xl': 'var(--breakpoint-2xl)',
      },
      transitionDuration: {
        instant: 'var(--duration-instant)',
        fast: 'var(--duration-fast)',
        base: 'var(--duration-normal)',
        slow: 'var(--duration-slow)',
        slower: 'var(--duration-slower)',
        slowest: 'var(--duration-slowest)',
      },
      transitionTimingFunction: {
        'ease-linear': 'var(--ease-linear)',
        'ease-in': 'var(--ease-in)',
        'ease-out': 'var(--ease-out)',
        'ease-in-out': 'var(--ease-in-out)',
        'ease-spring': 'var(--ease-editorial)',
        'ease-bounce': 'var(--ease-cinematic)',
      },
      animation: {
        'fade-in': 'fadeIn var(--duration-normal) var(--ease-out)',
        'slide-up': 'slideUp var(--duration-slow) var(--ease-out)',
        'green-glow': 'greenGlow 2s var(--ease-in-out) infinite',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
export default config
